---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new, new features, features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.12.0提供了一项新的增强功能。 
---
= Cloud Volumes ONTAP 9.12.0.中的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.12.0提供了一项新的增强功能。

最新版本的BlueXP还引入了其他功能和增强功能。 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["《BlueXP发行说明》"^]有关详细信息、请参见。



== 9.12.0 P1 (2022年12月15日)

Cloud Volumes ONTAP 9.12.0 P1现在可在AWS和Google Cloud中使用。此版本包含以下新增功能。



=== 在 AWS 中支持 m6id.32xlarge

现在、AWS中的m6id.32x大型EC2实例类型支持Cloud Volumes ONTAP。

有关更多详细信息、请转到link:reference-configs-aws.html["支持的配置页面"]。



== 升级说明

通读这些注释、了解有关升级到此版本的更多信息。



=== 如何升级

必须从BlueXP完成Cloud Volumes ONTAP 升级。您不应使用 System Manager 或命令行界面升级 Cloud Volumes ONTAP 。这样做可能会影响系统稳定性。

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["了解在收到BlueXP通知时如何升级"^](英文)



=== 支持的升级路径

您可以从9.11.1.版升级到Cloud Volumes ONTAP 9.12.0。BlueXP将提示您将符合条件的Cloud Volumes ONTAP 系统升级到此版本。



=== 所需版本的Connector

要部署新的Cloud Volumes ONTAP 9.12.0系统以及将现有系统升级到此版本、BlueXP  连接器必须运行3.9.24或更高版本。


TIP: 默认情况下，连接器会自动升级，因此您应运行最新版本。



=== 停机

* 升级单节点系统会使系统脱机长达 25 分钟，在此期间 I/O 会中断。
* 升级 HA 对无中断， I/O 不会中断。在此无中断升级过程中，每个节点会同时进行升级，以继续为客户端提供 I/O 。




=== 在AWS中使用C4、M4和R4 EC2实例类型进行升级

在AWS中、新的Cloud Volumes ONTAP部署不再支持C4、M4和R4 EC2实例类型。如果现有系统运行的是C4、M4或r4实例类型、则必须更改为c5、M5或R5实例系列中的实例类型。如果无法更改实例类型、则需要在升级之前启用增强型网络连接。

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["了解如何在具有C4、M4和R4 EC2实例类型的AWS中升级"^](英文)link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["了解如何更改Cloud Volumes ONTAP 的EC2实例类型"^](英文)

请参见link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp 支持"^]、了解有关终止这些实例类型的可用性和支持的详细信息。
